steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/c-internship-management-system:$SHORT_SHA
      - internship-backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/c-internship-management-system:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - c-internship-management-system
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/c-internship-management-system:$SHORT_SHA
      - --region=us-central1
      - --service-account=ims-runtime@$PROJECT_ID.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --ingress=all
      - --min-instances=0
      - --max-instances=2
      - --set-secrets=JWT_KEY=JWT_TOKEN:latest,DATABASE_URL=DATABASE_URL:latest
      - --set-env-vars=CORS_ALLOWED_ORIGINS=https://imsinternships.vercel.app,RESUME_BUCKET_NAME=ims-resumes-project-5b74f390-4444-4e81-92e

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/c-internship-management-system:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
